config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  searchkick
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :length, :director, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    if @review.save
      redirect_to @movie
    else
      render 'new'
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReviewApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movie_description %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length, id: :movie_length %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director, id: :movie_director %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: :movie_rating %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :movie_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %> <br><br>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em> <br><br>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td class="labeltd">Title </td>
                <td class="detail"><%= @movie.title %></td>
              </tr>
              <tr>
                <td class="labeltd">Description </td>
                <td class="detail"><%= @movie.description %></td>
              </tr>
              <tr>
                <td class="labeltd">Length </td>
                <td class="detail"><%= @movie.length%></td>
              </tr>
              <tr>
                <td class="labeltd">Director </td>
                <td class="detail"><%= @movie.director %></td>
              </tr>
              <tr>
                <td class="labeltd">Rating </td>
                <td class="detail"><%= @movie.rating %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_movie_review_path(@movie) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movie_path(@movie) %>